=== mukhtarov-denis/epam-training/lab3v1XML/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.epam.com/plants" 
    xmlns="http://www.epam.com/plants" 
    elementFormDefault="qualified">

    <xs:element name="name" type="xs:string" />
    <xs:element name="origin" type="xs:string"/>
    <xs:element name="stem_color" type="xs:string"/>
    <xs:element name="leaf_color" type="xs:string"/>
    <xs:element name="average_length" type="xs:integer"/>
    <xs:element name="min_temperature">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="15"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element> 
    <xs:element name="max_temperature">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="16"/>
                <xs:maxInclusive value="40"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="soil">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="PODZOLIC"/>
                <xs:enumeration value="GROUND"/>
                <xs:enumeration value="SOD_PODZOLIC"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="visuals">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="stem_color"/>
                <xs:element ref="leaf_color"/>
                <xs:element ref="average_length"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="light">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:boolean">
                    <xs:attribute name="note" type="xs:string" use="required" fixed="светолюбиво"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="water">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:positiveInteger">
                    <xs:attribute name="note" type="xs:string" use="required" fixed="мл. в неделю"/>
                </xs:extension>
             </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    
    <xs:element name="growing_tips">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="min_temperature"/>
                <xs:element ref="max_temperature"/>
                <xs:element ref="light"/>
                <xs:element ref="water"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="multiplying">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="LEAF"/>
                <xs:enumeration value="STALK"/>
                <xs:enumeration value="SEED"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="plant">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" />
                <xs:element ref="soil" />
                <xs:element ref="origin" />
                <xs:element ref="visuals" />
                <xs:element ref="growing_tips" />
                <xs:element ref="multiplying" />
            </xs:sequence>
            <xs:attribute name="idPlant" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    
    <!-- root element -->    
    <xs:element name="plants">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="plant" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== mukhtarov-denis/epam-training/lab3v1XML/plants_sort_by_water.xml
<?xml version="1.0" encoding="UTF-8"?><plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.epam.com/plants" xsi:schemaLocation="http://www.epam.com/plants plants.xsd"><plant idPlant="6"><name>Фиалка</name><soil>PODZOLIC</soil><origin>Беларусь</origin><visuals><stem_color>Зеленый</stem_color><leaf_color>Желтый</leaf_color><average_length>10</average_length></visuals><growing_tips><min_temperature>8</min_temperature><max_temperature>22</max_temperature><light note="светолюбиво">false</light><water note="мл. в неделю">50</water></growing_tips><multiplying>STALK</multiplying></plant><plant idPlant="4"><name>Рипсалидопсис</name><soil>SOD_PODZOLIC</soil><origin>Южная Америка</origin><visuals><stem_color>Зеленый</stem_color><leaf_color>Оранжевый</leaf_color><average_length>25</average_length></visuals><growing_tips><min_temperature>12</min_temperature><max_temperature>20</max_temperature><light note="светолюбиво">false</light><water note="мл. в неделю">100</water></growing_tips><multiplying>STALK</multiplying></plant><plant idPlant="2"><name>Герань</name><soil>GROUND</soil><origin>Южная Африка</origin><visuals><stem_color>Зеленый</stem_color><leaf_color>Красный</leaf_color><average_length>30</average_length></visuals><growing_tips><min_temperature>10</min_temperature><max_temperature>28</max_temperature><light note="светолюбиво">true</light><water note="мл. в неделю">200</water></growing_tips><multiplying>STALK</multiplying></plant><plant idPlant="1"><name>Роза</name><soil>GROUND</soil><origin>Франция</origin><visuals><stem_color>Зеленый</stem_color><leaf_color>Красный</leaf_color><average_length>80</average_length></visuals><growing_tips><min_temperature>15</min_temperature><max_temperature>24</max_temperature><light note="светолюбиво">true</light><water note="мл. в неделю">200</water></growing_tips><multiplying>SEED</multiplying></plant><plant idPlant="3"><name>Гастерия</name><soil>PODZOLIC</soil><origin>Южная Африка</origin><visuals><stem_color>Зеленый</stem_color><leaf_color>Розовый</leaf_color><average_length>15</average_length></visuals><growing_tips><min_temperature>10</min_temperature><max_temperature>24</max_temperature><light note="светолюбиво">true</light><water note="мл. в неделю">300</water></growing_tips><multiplying>STALK</multiplying></plant><plant idPlant="5"><name>Росянка</name><soil>PODZOLIC</soil><origin>Австралия</origin><visuals><stem_color>Зеленый</stem_color><leaf_color>Красный</leaf_color><average_length>25</average_length></visuals><growing_tips><min_temperature>4</min_temperature><max_temperature>27</max_temperature><light note="светолюбиво">true</light><water note="мл. в неделю">500</water></growing_tips><multiplying>STALK</multiplying></plant></plants>
